=== iqb-specifications/unit-index/unit-index.schema.json
{
  "$id": "unit-index@18.0",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Unit Index",
  "description": "Specification for the main data file for assessment units.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Short name/key/id of the unit as used in a specific testing.",
      "examples": [
        "ME2236a01",
        "G7224_py"
      ]
    },
    "uuid": {
      "type": "string",
      "description": "Universal id to identify versions and variants in many different assessments.",
      "examples": [
        "d19188fc-02e3-439e-9ff9-4f8280f9f01c",
        "https://w3id.org/iqb/unit/e4r5t6z7"
      ]
    },
    "modifiedAt": {
      "type": "string",
      "format": "date-time",
      "description": "Timestamp of last change. This is related to the index, not to the separate data blocks.",
      "examples": [
        "2026-04-09T13:15:10.977Z"
      ]
    },
    "label": {
      "type": "string",
      "description": "This data is usually taken as readable name or title in lists",
      "examples": [
        "Ein wunderbarer Ausflug",
        "Das Glücksrad"
      ]
    },
    "description": {
      "type": "string",
      "description": "This data can be used for notes/comments to better understand the purpose of the unit"
    },
    "userInterface": {
      "type": "object",
      "description": "Definition of visual presentation and interaction features.",
      "properties": {
        "player": {
          "type": "string",
          "description": "Verona player module to run the unit.",
          "examples": [
            "iqb-player-speedtest@4.1",
            "iqb-player-lottie@0.25"
          ]
        },
        "playerDependencies": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/externalDependency"
          }
        },
        "editor": {
          "type": "string",
          "description": "Verona player module to edit the unit ui.",
          "examples": [
            "iqb-editor-aspect@2.12"
          ]
        },
        "editorDependencies": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/externalDependency"
          }
        },
        "type": {
          "type": "string",
          "description": "Used to specify the data type of the UI.",
          "examples": [
            "iqb-aspect@5.0"
          ]
        },
        "definition": {
          "type": "string",
          "description": "Key to find the user interface definition (i.e. filename) or full stringified UI definition - depending on 'isDefinitionInline'.",
          "examples": [
            "H7876d4.voud.json",
            "<p>Bitte warte auf die Freigabe durch die Testleitung!</p>"
          ]
        },
        "isDefinitionInline": {
          "type": "boolean",
          "description": "If true the property 'definition' contains the full stringified UI definition.",
          "default": false
        },
        "modifiedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Timestamp of last change.",
          "examples": [
            "2026-04-09T13:15:10.977Z"
          ]
        }
      },
      "required": [
        "player"
      ],
      "additionalProperties": false
    },
    "codingScheme": {
      "$ref": "#/$defs/externalDataBlock"
    },
    "comments": {
      "$ref": "#/$defs/externalDataBlock"
    },
    "richNotes": {
      "$ref": "#/$defs/externalDataBlock"
    },
    "metadata": {
      "$ref": "#/$defs/externalDataBlock"
    },
    "items": {
      "$ref": "#/$defs/externalDataBlock"
    },
    "variables": {
      "$ref": "#/$defs/externalDataBlock"
    }
  },
  "required": [
    "id", "userInterface"
  ],
  "additionalProperties": false,
  "$defs": {
    "externalDataBlock": {
      "type": "object",
      "description": "External file as part of the unit data.",
      "properties": {
        "id": {
          "type": "string",
          "description": "Key to find the data block. Usually this is the full filename without path.",
          "examples": [
            "M2246.voxy.json"
          ]
        },
        "type": {
          "type": "string",
          "description": "Used to specify the data type of the block. Best pracise use <id>@<version> (see example)",
          "examples": [
            "isb-unit-ex@3.6"
          ]
        },
        "modifiedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Timestamp of last change. This is independent from the DateTime of the file in the file system.",
          "examples": [
            "2026-04-09T13:15:10.977Z"
          ]
        },
        "dependencies": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/externalDependency"
          }
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "externalDependency": {
      "type": "object",
      "description": "External file or service this unit's running or data processing depends on.",
      "properties": {
        "id": {
          "type": "string",
          "description": "Key to find the dependency. This can be a filename or url depending on the mode property.",
          "examples": [
            "GeoGebra.itcr.zip",
            "https://short-answer.IfBQ-codingservice.de"
          ]
        },
        "mode": {
          "type": "string",
          "description": "Used to specify the access mode of the dependency",
          "enum": [
            "WEB_SERVICE",
            "FILE",
            "FILE_UNPACK"
          ],
          "default": "FILE"
        }
      },
      "required": ["id"],
      "additionalProperties": false
    }
  }
}

=== iqb-specifications/unit-index/test/unit-index3.json
{
    "id": "ME2236a01",
    "uuid": "https://w3id.org/iqb/unit/e4r5t6z7",
    "modifiedAt": "2026-04-09T13:15:10.977Z",
    "label": "Ein wunderbarer Ausflug",
    "userInterface": {
        "player": "iqb-player-speedtest@4.1",
        "definition": "<p>Bitte warte auf Anweisungen der Testleitung!</p>",
        "isDefinitionInline": true
    }
}
